DROP TABLE IF EXISTS teams_colors;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS colors;
DROP TABLE IF EXISTS cities;

CREATE TABLE cities (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64)
);

CREATE TABLE colors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64)
);

CREATE TABLE teams (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64) UNIQUE,
  mascot VARCHAR(64),
  city_id INTEGER REFERENCES cities
);

CREATE TABLE teams_colors (
  id SERIAL PRIMARY KEY,
  team_id INTEGER REFERENCES teams,
  color_id INTEGER REFERENCES colors
);
