%YAML 1.2
---
tables:
  one: 
    tablename: languages
    columns:
      - name: id
        type: SERIAL
        options: PRIMARY KEY
      - name: name
        type: VARCHAR(64)
        options: UNIQUE
      - name: abbreviation
        type: VARCHAR(2)

  main: 
    tablename: movies
    columns:
      - name: id
        type: SERIAL
        options: PRIMARY KEY
      - name: title
        type: VARCHAR(128)
      - name: average_rating
        type: FLOAT
      - name: language_id
        type: INTEGER
        options: REFERENCES languages
  many:
    tablename: genres
    columns:
      - name: id
        type: INTEGER
        options: PRIMARY KEY
      - name: name
        type: VARCHAR(64)

  join:
    tablename: movies_genres
    columns:
      - name: id
        type: SERIAL
        options: PRIMARY KEY
      - name: movie_id
        type: INTEGER
        options: REFERENCES movies
      - name: genre_id
        type: INTEGER
        options: REFERENCES genres
